env:
  - GAIAMA_CONTENT_URL="https://gitlab.com/api/v4/projects/$GAIAMA_CONTENT_ID/repository/archive?sha=$TRAVIS_BRANCH&private_token=$GAIAMA_CONTENT_TOKEN"

language: node_js
cache: yarn

#branches:
#  only:
#    - develop
#    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4

script:
  - wget -O content.tgz $GAIAMA_CONTENT_URL
  - tar -xzf content.tgz -C content
  - yarn build
  #- yarn test

env:
  - CI=true

#before_deploy:
#  - yarn build

#deploy:
#  - provider: script
#    script: netlify deploy -s master -t $NETLIFY_ACCESS_TOKEN -p ./public
#    skip_cleanup: true
#    on:
#      branch: master
#      tags: true
#  - provider: script
#    script: netlify deploy -s dev -t $NETLIFY_ACCESS_TOKEN -p ./public
#    skip_cleanup: true
#    on:
#      branch: dev
