[Settings]
ID = "gaiama"

[build]
  base    = "/"
  publish = "public/"
  command = "wget -O content.tgz 'https://gitlab.com/api/v4/projects/$GAIAMA_CONTENT_ID/repository/archive?private_token=$GAIAMA_CONTENT_TOKEN&sha=$BRANCH' && npm rebuild sharp && mkdir content && tar -xzf content.tgz -C content && yarn build"
