[Settings]
ID = "gaiama"

[build]
  base    = "/"
  publish = "public/"
  command = "wget -O content.tgz \"https://gitlab.com/api/v4/projects/$GAIAMA_CONTENT_ID/repository/archive?sha=$BRANCH&private_token=$GAIAMA_CONTENT_TOKEN\" && npm rebuild sharp && mkdir content && tar -xzf content.tgz -C content && yarn build"

[context.production]
  environment = { NODE_ENV="production" }